language: objective-c
xcode_project: ShiftIt/ShiftIt.xcodeproj
xcode_scheme: ShiftIt
osx_image: xcode6.4
xcode_sdk: macosx10.9
before_install:
  - wget http://xquartz.macosforge.org/downloads/SL/XQuartz-2.7.6.dmg
  - hdiutil attach XQuartz-2.7.6.dmg
  - sudo installer -pkg /Volumes/XQuartz-2.7.6/XQuartz.pkg -target /
